import os, json, re

username = "antargfx"
repo     = "codelab"
base_url = f"https://{username}.github.io/{repo}"

entries = []

for name in os.listdir("."):
    # Skip hidden files/folders, the workflow folder, and this script itself
    if name.startswith(".") or name in ("generate-index.py", "index.html"):
        continue

    # Folder with index.html inside
    if os.path.isdir(name):
        if os.path.isfile(os.path.join(name, "index.html")):
            entries.append({"name": name, "url": f"{base_url}/{name}/"})

    # Standalone .html file (not index.html itself)
    elif name.lower().endswith(".html") and name.lower() != "index.html":
        label = re.sub(r"\.html$", "", name, flags=re.IGNORECASE)
        entries.append({"name": label, "url": f"{base_url}/{name}"})

# Natural sort
def natural_key(e):
    return [int(c) if c.isdigit() else c.lower() for c in re.split(r"(\d+)", e["name"])]

entries.sort(key=natural_key)

cards_html = ""
for e in entries:
    cards_html += f'''    <a class="card" href="{e['url']}" target="_blank" rel="noopener noreferrer">
      <h2>{e['name']}</h2>
      <p>{e['url']}</p>
    </a>\n'''

html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Antar's Projects</title>
<style>
body {{
  background: #0d1117;
  color: white;
  font-family: Arial, sans-serif;
  padding: 40px;
}}
h1 {{
  margin-bottom: 30px;
}}
.grid {{
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(250px, 1fr));
  gap: 20px;
}}
.card {{
  background: #161b22;
  border: 1px solid #30363d;
  border-radius: 16px;
  padding: 20px;
  text-decoration: none;
  color: white;
  transition: .2s;
  overflow: hidden;
  word-break: break-word;
}}
.card:hover {{
  border-color: #58a6ff;
  transform: translateY(-3px);
}}
</style>
</head>
<body>
<h1>Antar's Projects</h1>
<div class="grid">
{cards_html}</div>
<!-- Auto-generated by generate-index.py — do not edit manually -->
</body>
</html>"""

with open("index.html", "w") as f:
    f.write(html)

print(f"Generated index.html with {len(entries)} projects.")
